### ISSUE TITLE
trying to get things started.

### ISSUE THREAD

**Issue by wvdvegt** [RotaruDan/test-users#82]
Hi

I'm trying to get the logging to work but keep hitting 401 access denied errors.

Both
http://<ip>:3000/api/health
http://<ip>:3000/api/login

work and the second rest calls nicely returns an authToken.

But the next (POST) call:
http://<ip>:3000/api/collector/start/:<gamecode>
keeps returning 401 no matter if i pass
Authorization: a:,
or
Authorization: a:<authToken from login>
header

If I pass:
Authorization: a:<username>,
returns a 404 not found for my developer username returned by the login REST call.

Any clues what causes this?

Best Regard
Wim van der Vegt / OUNL

**Comment by gorco** [comment]
http://:3000/api/collector/start/: with a: authorization returns you 401 error if you have a class created but you didn't configure it allowing anonymous players.
https://github.com/e-ucm/rage-analytics/wiki/Set-up-a-class

You don't have to pass a authorization header in a login call. Maybe this provoke the error, but can you write us the steps that you are following and the calls? thanks.

Best regads.

**Comment by wvdvegt** [comment]
Hi 
Thanks for responding,

As a developer I can't remember seeing these options (I'll have a look again tomorrow).

Best Regards
Wim van der Vegt / OUNL

**Comment by gorco** [comment]
Sorry, the problem was the call, should be 

```
http://localhost:3000/api/proxy/gleaner/collector/
```

 where gleaner is the name of the registered application in a2.
https://github.com/e-ucm/rage-analytics/wiki/A2-Admin-view

**Comment by RotaruDan** [comment]
Hi, 

This issue has been resolved. 

Closing.
