### ISSUE TITLE
Api Documentation

### ISSUE THREAD

**Issue by wvdvegt** [RotaruDan/test-users#85]
Hi

The documentation says that the Authorization header is either
**a:**
**a: < playerName >**
*\* < authToken >**

Trying a simple rest call **http://<ip>:3000/api/games/public** and use first last or last format (ie Authorization: a: or Authorization: <token>) I get an error message that the format is:
**{"message":"Format is Authorization: Bearer [token]"}**

The token is the one I got from the login call.

If I add a Bearer prefix to the token or 'a:' I get 404 when I try to retrieve al public games with 
**/api/games/public** and a message **{"message":"Not Found"}**.

Can you please e-mail/pm me some wGet statements and their output (it still is very confusing and besides health/login nothing seems to work like it should)?

Best Regards
Wim van der Vegt / OUNL

**Comment by wvdvegt** [comment]
If I add an 
**Authorization: Bearer a:** (other values without Bearer all give errors about missing authorization)
Header the a service (where the tracking code is one of an open and public game) like:
http://<ip>:3000/api/gleaner/start/:565d6da5b4c1dc4200bd50dagguva4nbikqsq0k9
I get a new 401 response
**{
  "message": "jwt malformed"
}**

**Comment by gorco** [comment]
The call is `http://:3000/api/gleaner/collector/start/:trackingCode` and the header `a:` (without Bearer, this word is for the token obtained with the login call or the token that returns the collector/start).

**Comment by wvdvegt** [comment]
Hi

Many thanks! 

It (finally) starts working if i remove the colon from the tracking code and pass a username as Authorization value (so veg and not a:veg as the online REST documentation suggest).

To summarize:

The documentation at http://<ip>:3300/ is incorrect it seems. According to what now works 
1) the suggested url is wrong (proxy/gleaner is missing)
2) in the case 2 of the Authorization header (should read 'playerName' instead of 'a:playerName').
3) there should be no colon before the trackingcode.

Please try to make error messages a bit more descriptive (and not pointing in a wrong direction). Also URL's not pointing to REST services should not retrun json (like <ip>:3300/api).

Best Regards
Wim van der Vegt / OUNL

**Comment by wvdvegt** [comment]
Btw the documentation on https://github.com/e-ucm/rage-analytics/wiki/Tracking-code also contains a typo. It says Issue a GET where it should read POST (with an empty body but with an Authorization header, values a:, <username> or <userToken>).

'Issue a  GET localhost:3000/api/proxy/gleaner/start/:trackingCode  with the provided tracking code. Receive in the response the authorization token ( authToken ) needed to identify the following requests.'

**Comment by RotaruDan** [comment]
Another API doc issue found: https://github.com/e-ucm/a2/blob/master/routes/signup.js#L13 should indicate username/password as String and not String[]. Pending to be fixed.
