### ISSUE TITLE
Actor

### ISSUE THREAD

**Issue by wvdvegt** [RotaruDan/test-users#88]
I'm seeing somewhat strange behavior and wonder if it's correct.

If I issue a start request the name of  author is always different and the account name always Anonymous. No matter if I issue the start directly with a userToken or Login first.

I expect this behavior only when issuing a start with 'a:' as token as anonymous users are always different. xAPI as far as I can tell uses the Actor in queries so it will be difficult to combine multiple sessions by one user this way (unless something is changed in the trace by the server).

**Comment by manuel-freire** [comment]
Of course, different sessions by anonymous users will not be combined.

Login information should be preserved via an `X-Gleaner-User` header [added by A2](https://github.com/e-ucm/a2/blob/master/routes/proxy.js#L108) and interpreted by the [backend](https://github.com/e-ucm/rage-analytics-backend/blob/master/routes/collector.js#L36) to be used as the xAPI actor.  Note that HTTP headers are supposed to be case-insensitive. 

Can you confirm that the xAPI traces do not preserve correct Actors by checking in OpenLRS or Back's logs? Otherwise, we will close the issue as "expected behaviour".

**Comment by manuel-freire** [comment]
@wvdvegt I edited your comment to conform to standard issue formatting (for example, your name is implied by your github user)

**Comment by wvdvegt** [comment]
I only see the following headers 

`Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, Authorization2
Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT, DELETE
Access-Control-Allow-Credentials: true
Connection: keep-alive
Content-Length: 320
Content-Type: application/json; charset=utf-8
Date: Mon, 11 Jan 2016 13:31:52 GMT
ETag: W/"140-UYOfQ36ctcB/9J9O7i4OnA"
X-Powered-By: Express`

So no X-Gleaner-User header.

**Comment by manuel-freire** [comment]
As expected - this header is created by `A2` for use by rage-analytics-backend (`Back`) when `A2` receives an authenticated incoming connection from a tracker (remember: `A2` is a proxy; the request sent to the server-side assets proxied by `A2` can be transparently altered by `A2`), and this header is therefore never made visible to tracker clients. You cannot inspect it unless you stand between `A2` and `Back`.

**Comment by wvdvegt** [comment]
I do not have access to the back-end and besides do not know where to look.

I'll have a look it the actor part remains the same during subsequent runs of non anonymous users.

**Comment by manuel-freire** [comment]
You _do_ have access to the back-end (at least if you run things locally and have a look at the back-end logs: `./rage-analytics.sh logs back`). Checking to see if

> the actor part remains the same during subsequent runs of non anonymous users

 should also work (although you won't get to see the exact statement that is being written).

**Comment by wvdvegt** [comment]
I do not have (user/administrative) access to the Server's command prompt (so cannot run bash scripts). I can only see the web-pages. But I'll ask our administrator.
